default_language_version:
  python: python3.11

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
        exclude: LICENSE

  - repo: local
    hooks:
      - id: isort
        name: Format import w/ isort
        entry: poetry run isort --settings-path pyproject.toml .
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: black
        name: Format black
        entry: poetry run black --config pyproject.toml .
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: ruff
        name: Lint w/ ruff
        entry: poetry run ruff check --config pyproject.toml .
        language: system
        types: [python]
        args: [--exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: detect-private-key

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
