---
services:
  jenkins:
    container_name: jenkins_vulnerable
    hostname: jenkins_vuln_instance
    image: jenkins/jenkins:2.441
    ports:
      - "1234:8080"
      - "50000:50000" # for debugging??
    volumes:
      - jenkins_data:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Dhudson.security.CLI=true # CLI required for testing CVE-2024-23897

volumes:
  jenkins_data:
